In [1]:
from moexalgo import Market, Ticker

In [2]:
eq = Market('EQ')
eq.tickers()

,SECID,BOARDID,SHORTNAME,PREVPRICE,LOTSIZE,FACEVALUE,STATUS,BOARDNAME,DECIMALS,SECNAME,...,PREVDATE,ISSUESIZE,ISIN,LATNAME,REGNUMBER,PREVLEGALCLOSEPRICE,CURRENCYID,SECTYPE,LISTLEVEL,SETTLEDATE
0,ABRD,TQBR,АбрауДюрсо,355.800,10,1.00,A,Т+: Акции и ДР - безадрес.,1,Абрау-Дюрсо ПАО ао,...,2023-08-02,98000184,RU000A0JS5T7,Abrau-Durso ao,1-02-12500-A,355.800,SUR,1,3,2023-08-04
1,ACKO,TQBR,АСКО ао,3.580,100,1.00,N,Т+: Акции и ДР - безадрес.,2,АСКО ПАО ао,...,2023-08-02,536000000,RU000A0JXS91,ASKO ao,1-01-52065-Z,3.580,SUR,1,3,2023-08-04
2,AFKS,TQBR,Система ао,18.647,100,0.09,A,Т+: Акции и ДР - безадрес.,3,"АФК ""Система"" ПАО ао",...,2023-08-02,9650000000,RU000A0DQZE3,AFK Sistema,1-05-01669-A,18.673,SUR,1,1,2023-08-04
3,AFLT,TQBR,Аэрофлот,45.260,10,1.00,A,Т+: Акции и ДР - безадрес.,2,Аэрофлот-росс.авиалин(ПАО)ао,...,2023-08-02,3975771215,RU0009062285,Aeroflot,1-01-00010-A,45.240,SUR,1,1,2023-08-04
4,AGRO,TQBR,AGRO-гдр,1170.000,1,0.00,A,Т+: Акции и ДР - безадрес.,1,ГДР ROS AGRO PLC ORD SHS,...,2023-08-02,0,US7496552057,GDR ROS AGRO PLC ORD SHS,None,1170.400,SUR,D,1,2023-08-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,YNDX,TQBR,Yandex clA,2709.400,1,0.01,A,Т+: Акции и ДР - безадрес.,1,PLLC Yandex N.V. class A shs,...,2023-08-02,326342270,NL0009805522,PLLC Yandex N.V.,None,2697.000,SUR,1,1,2023-08-04
244,YRSB,TQBR,ТНСэнЯр,1014.000,10,1.00,A,Т+: Акции и ДР - безадрес.,0,ТНС энерго Ярославль ПАО ао,...,2023-08-02,17143584,RU000A0D8760,TNS energo Yaroslavl' ao,1-01-50099-A,1014.000,SUR,1,3,2023-08-04
245,YRSBP,TQBR,ТНСэнЯр-п,250.000,10,1.00,A,Т+: Акции и ДР - безадрес.,1,ТНС энерго Ярославль ПАО ап,...,2023-08-02,4507320,RU000A0D88B3,TNS energo Yaroslavl' (pref),2-01-50099-A,250.000,SUR,2,3,2023-08-04
246,ZILL,TQBR,ЗИЛ ао,3600.000,1,1000.00,A,Т+: Акции и ДР - безадрес.,0,Завод им. И.А.Лихачева ПАО ао,...,2023-08-02,2659962,RU0009086193,ZIL ao,1-02-00036-A,3600.000,SUR,1,3,2023-08-04
247,ZVEZ,TQBR,ЗВЕЗДА ао,7.500,1000,0.10,A,Т+: Акции и ДР - безадрес.,3,ЗВЕЗДА ПАО ао,...,2023-08-02,562020480,RU0009091300,Zvezda ao,1-01-00169-D,7.485,SUR,1,3,2023-08-04

In [3]:
eq.stats()

,SECID,BOARDID,BID,BIDDEPTH,OFFER,OFFERDEPTH,SPREAD,BIDDEPTHT,OFFERDEPTHT,OPEN,...,OPENPERIODPRICE,SEQNUM,SYSTIME,CLOSINGAUCTIONPRICE,CLOSINGAUCTIONVOLUME,ISSUECAPITALIZATION,ISSUECAPITALIZATION_UPDATETIME,ETFSETTLECURRENCY,VALTODAY_RUR,TRADINGSESSION
0,ABRD,TQBR,367.200,63,367.400,8,0.200,13561,15859,360.600,...,360.600,20230803162458,2023-08-03 16:24:58,None,None,3.598567e+10,16:23:51,None,595228836,1
1,ACKO,TQBR,NaN,0,NaN,0,0.000,0,0,NaN,...,NaN,20230803100025,2023-08-03 10:00:25,None,None,1.918880e+09,00:00:00,None,0,1
2,AFKS,TQBR,18.779,3,18.786,5,0.007,68872,74994,18.704,...,18.704,20230803162459,2023-08-03 16:24:59,None,None,1.812752e+11,16:23:59,None,333914745,1
3,AFLT,TQBR,45.700,1876,45.720,1,0.020,394609,290847,45.110,...,45.110,20230803162459,2023-08-03 16:24:59,None,None,1.817325e+11,16:23:57,None,423748902,1
4,AGRO,TQBR,1153.600,6,1153.800,80,0.200,55826,78379,1160.200,...,1160.200,20230803162459,2023-08-03 16:24:59,None,None,NaN,None,None,301396242,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,YNDX,TQBR,2762.400,30,2763.200,100,0.800,137715,96519,2709.400,...,2709.400,20230803162459,2023-08-03 16:24:59,None,None,9.020100e+11,16:23:58,None,2338644196,1
244,YRSB,TQBR,1400.000,1,1412.000,3,12.000,381,19,1052.000,...,1052.000,20230803162400,2023-08-03 16:24:00,None,None,2.424103e+10,16:21:20,None,54909840,1
245,YRSBP,TQBR,337.000,1,337.500,4,0.500,3132,485,250.000,...,250.000,20230803162455,2023-08-03 16:24:55,None,None,1.518967e+09,16:23:27,None,71736820,1
246,ZILL,TQBR,3585.000,9,3600.000,6,15.000,2028,4768,3600.000,...,3600.000,20230803162436,2023-08-03 16:24:36,None,None,9.575863e+09,16:11:41,None,3395495,1
247,ZVEZ,TQBR,7.520,5,7.570,7,0.050,797,787,7.460,...,NaN,20230803162459,2023-08-03 16:24:59,None,None,4.209533e+09,16:22:06,None,8927355,1

In [4]:
moex = Ticker('MOEX/TQBR')
moex.info()

                                                        title           value
SHORTNAME                  Краткое наименование ценной бумаги        МосБиржа
LOTSIZE      Количество ценных бумаг в одном стандартном лоте              10
STATUS      Индикатор "торговые операции разрешены/запрещены"               A
DECIMALS                       Точность, знаков после запятой               2
MINSTEP     Минимально возможная разница между ценами, ука...            0.01
ISSUESIZE                                       Объем выпуска      2276401458
ISIN        Международный идентификационный код ценной бумаги    RU000A0JR4A1
LATNAME     Наименование финансового инструмента на англий...  MoscowExchange
CURRENCYID                                    Валюта расчетов             SUR
SECTYPE                                     Тип ценной бумаги               1
LISTLEVEL                                    Уровень листинга               1

In [5]:
moex.orderbook()

,BOARDID,SECID,BUYSELL,PRICE,QUANTITY,SEQNUM,UPDATETIME,DECIMALS
0,TQBR,MOEX,S,133.79,53,20230803162459,16:24:58,2
1,TQBR,MOEX,S,133.77,4,20230803162459,16:24:58,2
2,TQBR,MOEX,S,133.76,58,20230803162459,16:24:58,2
3,TQBR,MOEX,S,133.75,32,20230803162459,16:24:58,2
4,TQBR,MOEX,S,133.72,500,20230803162459,16:24:58,2
5,TQBR,MOEX,S,133.70,421,20230803162459,16:24:58,2
6,TQBR,MOEX,S,133.66,3,20230803162459,16:24:58,2
7,TQBR,MOEX,S,133.64,124,20230803162459,16:24:58,2
8,TQBR,MOEX,S,133.63,4187,20230803162459,16:24:58,2
9,TQBR,MOEX,S,133.62,210,20230803162459,16:24:58,2
10,TQBR,MOEX,B,133.61,209,20230803162459,16:24:58,2
11,TQBR,MOEX,B,133.60,7643,20230803162459,16:24:58,2
12,TQBR,MOEX,B,133.59,145,20230803162459,16:24:58,2
13,TQBR,MOEX,B,133.58,70,20230803162459,16:24:58,2
14,TQBR,MOEX,B,133.57,111,20230803162459,16:24:58,2
15,TQBR,MOEX,B,133.56,82,20230803162459,16:24:58,2
16,TQBR,MOEX,B,133.55,751,20230803162459,16:24:58,2
17,TQBR,MOEX,B,133.54,318,20230803162459,16:24:58,2
18,TQBR,MOEX,B,133.53,59,20230803162459,16:24:58,2
19,TQBR,MOEX,B,133.52,48,20230803162459,16:24:58,2

In [6]:
moex.candles('2023-01-01', limit=1000)

,open,close,high,low,value,volume,begin,end
0,95.40,95.40,95.40,95.40,240408.0,2520.0,2023-01-03 09:00:00,2023-01-03 09:59:59
1,95.40,95.42,96.15,94.90,59790027.4,627080.0,2023-01-03 10:00:00,2023-01-03 10:59:59
2,95.42,95.65,95.90,95.40,13410778.3,140170.0,2023-01-03 11:00:00,2023-01-03 11:59:59
3,95.62,95.47,95.65,95.43,5233924.4,54810.0,2023-01-03 12:00:00,2023-01-03 12:59:59
4,95.45,95.30,95.48,95.25,7772928.6,81510.0,2023-01-03 13:00:00,2023-01-03 13:59:59
...,...,...,...,...,...,...,...,...
995,111.54,111.49,111.70,111.17,101552581.4,911390.0,2023-04-07 14:00:00,2023-04-07 14:59:59
996,111.49,111.34,111.55,111.30,21130252.9,189680.0,2023-04-07 15:00:00,2023-04-07 15:59:59
997,111.34,111.42,111.53,111.33,35431894.8,318030.0,2023-04-07 16:00:00,2023-04-07 16:59:59
998,111.50,111.60,111.70,111.44,35873514.3,321370.0,2023-04-07 17:00:00,2023-04-07 17:59:59
999,111.61,111.71,111.71,111.50,16530192.2,148080.0,2023-04-07 18:00:00,2023-04-07 18:49:13

In [7]:
imoex = Ticker('IMOEX')
imoex.info()

                                           title            value
SECID                                Код индекса            IMOEX
BOARDID                                    Режим             SNDX
NAME                                Наименование  Индекс МосБиржи
DECIMALS          Точность, знаков после запятой                2
SHORTNAME                   Наименование индекса  Индекс МосБиржи
ANNUALHIGH  Максимальное значение индекса за год          3123.45
ANNUALLOW    Минимальное значение индекса за год          1775.04
CURRENCYID                        Валюта расчета              RUB
CALCMODE                         Принцип расчета             None

In [8]:
imoex.candles('2020-01-01', interval=1, limit=500)

,open,close,high,low,value,volume,begin,end
0,3059.20,3062.08,3063.66,3057.36,5.614901e+08,0.0,2020-01-03 10:00:00,2020-01-03 10:00:59
1,3062.07,3064.59,3065.64,3061.65,3.335770e+08,0.0,2020-01-03 10:01:00,2020-01-03 10:01:59
2,3065.17,3068.52,3068.52,3065.13,2.777729e+08,0.0,2020-01-03 10:02:00,2020-01-03 10:02:59
3,3068.75,3069.34,3070.16,3067.80,1.851880e+08,0.0,2020-01-03 10:03:00,2020-01-03 10:03:59
4,3069.88,3071.54,3071.54,3069.80,1.785591e+08,0.0,2020-01-03 10:04:00,2020-01-03 10:04:59
...,...,...,...,...,...,...,...,...
495,3073.83,3074.45,3074.60,3073.78,1.110228e+08,0.0,2020-01-03 18:15:00,2020-01-03 18:15:59
496,3074.45,3074.52,3074.68,3074.40,7.817579e+07,0.0,2020-01-03 18:16:00,2020-01-03 18:16:59
497,3074.47,3075.02,3075.02,3074.41,1.195468e+08,0.0,2020-01-03 18:17:00,2020-01-03 18:17:59
498,3075.02,3075.22,3075.35,3074.95,9.306601e+07,0.0,2020-01-03 18:18:00,2020-01-03 18:18:59
499,3075.22,3074.57,3075.29,3074.54,9.513415e+07,0.0,2020-01-03 18:19:00,2020-01-03 18:19:59